### ISSUE TITLE
Add example for overriding rules...

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-api-style-guide#51]
In [Azure Ruleset Readmen](https://github.com/Azure/azure-api-style-guide/blob/main/docs/azure-ruleset.md#azure-ruleset) we talk about overriding the rule set. We should show an example here of how to do this.

**Comment by mikekistler** [comment]
I've tested the override support in Spectral and it seems to work.  Here's an example:
```
extends:
  - ../azure-api-style-guide/spectral.yaml
overrides:
  # Turn off rules for cognitive svcs APIs
  - files:
      - specification/cognitiveservices/**/*.json
    rules:
      # az-operation-id: off
      az-version-policy: off
      az-version-convention: off
```

Unfortunately, the override support is a feature of Spectral v6, and the VSCode plugin for Spectral currently uses Spectral v5.9, so the overrides do not work when using the Spectral VSCode plugin.

It looks like there is an effort to get the Spectral VSCode plugin updated to v6:

https://github.com/stoplightio/vscode-spectral/issues/107
